# Generated by Django 6.0.5 on 2026-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Loyer mensuel')),
                ('mileage', models.IntegerField(verbose_name='Kilométrage')),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], max_length=20, verbose_name='Type de carburant')),
                ('transmission', models.CharField(choices=[('manuel', 'Manuelle'), ('automatique', 'Automatique')], max_length=20, verbose_name='Boîte de vitesses')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('description', models.TextField(verbose_name='Description')),
                ('images', models.JSONField(default=list, help_text="Liste d'URLs d'images", verbose_name='Images')),
                ('vehicle_type', models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location')], max_length=10, verbose_name='Type de véhicule')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_vehicles', 'Peut gérer tous les véhicules (CRUD)'), ('can_change_vehicle_type', 'Peut basculer un véhicule de vente à location et inversement')],
            },
        ),
    ]
