# Generated by Django 6.0.5 on 2026-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rent_duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Durée minimale de location en mois', null=True),
        ),
    ]
