# Generated by Django 6.0.5 on 2026-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_rent_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ref',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence'),
        ),
    ]
