# Generated by Django 6.0.5 on 2026-06-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_images_vehicleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/%Y/%m/', verbose_name='Images'),
        ),
    ]
