# Generated by Django 6.0.5 on 2026-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_remove_folder_documents_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='validation_comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire de validation (admin)'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire du client'),
        ),
    ]
