# Generated by Django 6.0.5 on 2026-06-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_validation_comment_alter_folder_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='folder',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='folder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
    ]
